name: Clear Changes

on:
  workflow_dispatch:

jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.x'
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python clearChanges.py ${{ secrets.BOT_TOKEN }} ${{ secrets.CF_ACCOUNT_ID }} ${{ secrets.CF_TOKEN }} ${{ secrets.NAMESPACE }}
