name: Get Records

on:
  workflow_dispatch:

jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python Records.py
        
      - name: Commit changes
        run: |
          git config --global user.email "twhlynch@gmail.com"
          git config --global user.name "twhlynch"
          git add stats_data/sorted_leaderboard_records.json
          git add stats_data/leaderboard_levels.json
          git add stats_data/empty_leaderboards.json
          git add stats_data/user_finishes.json
          git add stats_data/sole_victors.json
          git add stats_data/difficulty_records.json
          git add stats_data/difficulty_lengths.json
          git commit -m "Records"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
