name: Update records

on:
  schedule:
    - cron: '0 17 1 * *'
  workflow_dispatch:

jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scripts/records.py

      - name: Commit changes
        run: |
          git config --global user.email "twhlynch.index@gmail.com"
          git config --global user.name "twhlynch"
          git add stats_data/*
          git commit -m "Update Records"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
