name: Get statistics

on:
  workflow_dispatch:

jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python Tipping.py
        
      - name: Commit changes
        run: |
          git config --global user.email "twhlynch.index@gmail.com"
          git config --global user.name "twhlynch"
          git add stats_data/statistics.json
          git commit -m "statistics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
