name: Update Stats

on:
  schedule:
    - cron: '0 5 * * *' # run every day at midnight UTC
  workflow_dispatch:

jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update Python
        run: pip install --upgrade pip

  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python getStats.py ${{ secrets.BOT_TOKEN }}
        
      - name: Commit changes
        run: |
          git config --global user.email "twhlynch@gmail.com"
          git config --global user.name "twhlynch"
          git add stats_data/*
          git commit -m "Update Stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
