name: Update diff.json

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC
  workflow_dispatch:
  
jobs:
  update-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Update diff.json
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Run script
        run: node diff.mjs
        
      - name: Commit changes
        run: |
          git config --global user.email "twhlynch@gmail.com"
          git config --global user.name "twhlynch"
          git add diff.json
          git add stats-data.json
          git commit -m "Update diff"
          git push
